#!/bin/bash

#https://stackoverflow.com/questions/29145370/docker-initialize-mysql-database-with-schema
# start db

set -e
set -x

# first, if the /var/lib/mysql directory is empty, unpack it from our predefined db
[ "$(ls -A /var/lib/mysql)" ] && echo "Running with existing database in /var/lib/mysql" || ( echo 'Populate initial db'; tar xpzvf default_mysql.tar.gz )

ps -e
# /usr/sbin/mysqld_safe --user root
# service mysqld start
/usr/sbin/mysqld --user root
